baseURL: "https://yassinemankai.netlify.app/"
languageCode: "en-us"
title: "YM_Portfolio"
theme: hugo-profile

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    - identifier: projects
      name: Projects
      title: Projects
      url: /projects
      weight: 1

params:
  title: "Personal website"
  description: "Personal website"
  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
    disableAchievements: true
  #    disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Yassine Mankai."
    subtitle: "I am a passionate 3D Engineer"
    content: "I am interested in both the algorithmic and creative aspects of computer graphics."
    image: "/uploads/photo.jpg"
    button:
      enable: true
      name: "Resume"
      url: https://telecomparis.cvdesignr.com/p/61c206fd5ae3a
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/YassineMankai/
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ymankai/

  # About
  about:
    enable: true
    title: "About Me"
    content: |-
      I am a software engineer with a passion for the 3D world. I have a background in computer science and mathematics, and I have a keen interest in the intersection of technology and the entertainment business (games and movies). 
      
      I am detail-oriented, pragmatic and eager to learn.

      I am currently looking for a R&D oriented opportunity as a computer graphics engineer.

    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "C++"
        - "OpenGL & GLSL"
        - "Unity3D & C"
        - "Git"
        - "Blender & Python"

  # Experience
  experience:
    enable: true
    items:
      - job: "3D engineer (intern)"
        company: "Des Vents Clairs"
        date: "Mar 2022 - present"
        featuredLink:
          enable: true
          name: "OpennMfx"
          url: "https://openmesheffect.org/"
        content: |
          I am currently working on a project that will introduce a way to exchange parametric shapes between multiple DCCs.
          
          OpenMfx is a plug-in standard for 3D mesh processing effects. 
          
          Role: 
            - Participate in the development of the API.
            - Expand the bank of procedural geometric effects available with OpenMfx. 
            - Contribute to the integration of OpenMfx effects in Blender and Unity.

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Master (M2): Computer Graphics"
        school:
          name: "Institut Polytechnique de Paris"
          url: "https://www.ip-paris.fr/en"
        date: "2019 - 2022"
        content: |-
          Courses
          
          - Digital representation and analysis of shapes: fundamental concepts for creating and analyzing shapes on the computer (smooth curves, meshes, implicit function, ...)
          
          - Computer Animation: practical implementation of animation techniques (procedural motion, interactive shape deformations, skeletal and skinning character animation, physics-based simulation, ...)
          
          - Image Synthesis: rendering equation, standard illumination, shading, reflectance models, rendering algorithms (rasterization, ray tracing), hierarchical spatial data structures

          - Computational Geometry: convex envelopes, Delaunay triangulation, point cloud reconstruction
     
      - title: "Engineering Degree"
        school:
          name: "Telecom Paris"
          url: "https://www.telecom-paris.fr/en/home"
        date: "2019 - 2022"
        GPA: "3.99 out of 4.0"
        content: |-
          Telecom Paris is a highly selective school and has one of France's top five graduate engineering programs. It is considered the leading French school in Information and Communication Technology.
          
          -1st year: Computer Science Basics, Applied Mathematics
          
          -2nd year: Double Major in "Computer Graphic & Interactive Systems" and "Image Processing"
         
          -3rd year: IGD Master (IPP)
      - title: "CPGE, MPSI/MP*"
        school:
          name: "Institut préparatoire aux études scientifiques et techniques (IPEST)"
        date: "2017 - 2019"
        content: |
          Intensive two-year program (math & physics) preparing for the competitive entrance examinations to the French ‘Grandes Écoles’
          
          admitted to:
            
            - Concours Centrale-Supélec
            
            - Concours commun Mines-Ponts


  # projects
  projects:
    enable: true

  #Contact
  contact:
    enable: true
    content: My inbox is always open !
    email: yassine.mankai@outlook.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/YassineMankai/
      linkedin: https://www.linkedin.com/in/ymankai/